### ISSUE TITLE
Left click / right click not bringing up profession window

### ISSUE THREAD

**Issue by Incandio** [cr4ckp0t/ElvUI_Professions#1]
Everything else works fine including shift modifier for cooking and arch. Using ELVUI 12.03. Got your datatext in a custom bar.

**Comment by fubaWoW** [comment]
working version here:
https://github.com/fubaWoW/ElvUI_Professions

never uploaded it, but i updated Lockslap's Version every Expansion for just myself :P

**Comment by cr4ckp0t** [comment]
Are you using a non-English version of WoW? The datatext works just fine for me. That's why I have only been doing interface number updates, because no one was reporting that it did not work. I can't fix what I don't know is broken.

If you create a fix for any of my work, please create a pull request. I have no issue merging it and giving credit. I fully support open source software!

**Comment by Incandio** [comment]
Hi, it was actually working intermittently for me (English version). There is another addon called Autobar that had issues with loading profession windows, though it was fixed recently. I have no idea if it's related, but you might want to check out this thread: https://us.forums.blizzard.com/en/wow/t/macros-for-professions-broken-since-82-or-more-recently/437756
and this forum https://muffinmangames.com/forum/index.php?topic=939.0
